### ISSUE TITLE
What is delay() supposed to do?

### ISSUE THREAD

**Issue by helgoboss** [rxRust/rxRust#106]
@M-Adoo I've a question regarding the `delay` operator. I thought it delays the submission of source items (as e.g. in rxjs) but in my case it seems to have the effect that the complete subscription is delayed. Once the subscription is done (after the delay), items are emitted immediately.

**Comment by M-Adoo** [comment]
Yes,  you are right. In fact  scheduler currently in a very rough stage，and need to invest energy to do better design.

**Comment by helgoboss** [comment]
Thanks, I understand. At least, for operators like `observe_on()`, the current `Scheduler` trait seems to be okay. It allowed me to easily write a run-loop scheduler which executes stuff on an external run loop. I guess the challenge comes with operators that need delays or time intervals.
