### ISSUE TITLE
Consider replacing PayloadCopy with Clone bound

### ISSUE THREAD

**Issue by helgoboss** [rxRust/rxRust#110]
In the last months I have worked a lot with rxRust in a real-world application. Overall, it works quite well. Although many operators are not available yet, it proved to be very useful already and in some areas it's even indispensable for me.

In some areas it' still a bit hard to use, compared to other Rx implementations. Obviously this is partly related to the nature of Rust itself, which sometimes has to sacrifice convenience for safety - this is totally fine and people who use Rust appreciate this anyway. But there are a few other aspects about rxRust which I think could be improved a bit so that it becomes easier to use.

One of them is the requirement for `PayloadCopy`. I found that in practice, I often deal with items which don't implement `Copy`. Because I don't want them to be cloned a dozen times when sending them through an observable chain, I often put them into an `Rc<T>`. AFAIK there's no way to implement `PayloadCopy` for `Rc<T>`, so I end up wrapping it in a custom `Payload<T>` type which implements `PayloadCopy` (by cloning its value). Of course, this `Payload` type then becomes part of my function signatures - a part of the public API, in case of a library. This is quite verbose.

The verbosity of having an extra wrapper could be prevented if rxRust would be satisfied with items that implement `Clone`. I know, the initial argument for requiring `Copy`/`PayloadCopy` was to make it harder for users to do anything stupid performance-wise (see #74). But IMHO it would be better to just mention this in the docs instead of making rxRust harder to use.

@M-Adoo What do you think?

**Comment by M-Adoo** [comment]
Thanks for your time.  Yes, I found same problem when I use rxRust in my project but not so painful as you. I'm not use so much Rc.

It's good to me use `Clone` instead of  `Copy/PayloadCopy`, and remind in document.   Would you open a pr to do it ? I'll glad to accept it and release a new version.

**Comment by helgoboss** [comment]
Thank you! Okay, I will open a PR within the next days.
