### ISSUE TITLE
I have feature request

### ISSUE THREAD

**Issue by jakobneufeld** [rxRust/rxRust#117]
Maybe this feature already exists, but is there a PublishSubject or a BehaviouralSubject or any kind of Subject in rxRust.

Kind Regards, Jakob.

PS: I love your library! 👍

**Comment by M-Adoo** [comment]
We already have a base `Subject`.
```rust
     let mut i = 0;
    {
      let mut subject = Subject::new();
      subject.clone().subscribe(|v| i = v * 2);
      subject.next(1);
    }
    assert_eq!(i, 2);
```
