### ISSUE TITLE
Add support for wasm

### ISSUE THREAD

**Issue by pickfire** [rxRust/rxRust#118]
Allows frontend web frameworks to use rxrust such as seed and stuff.

**Comment by M-Adoo** [comment]
I would like to have this，but  there is no time plan.

**Comment by phenax** [comment]
+1 Need this

**Comment by utilForever** [comment]
A month ago, I modified this crate to support WASM and worked well in Javascript.
I'll work this feature in future. (about in 1~2 month(s)?) 😆
