### ISSUE TITLE
GTK-rs and observe_on

### ISSUE THREAD

**Issue by leinardi** [rxRust/rxRust#120]
Hi, I'm new to Rust but pretty familiar with ReactiveX (both RxJava and RxPy).
I'm currently trying to write a GTK application with Rust and I was wondering if I could use RxRust for this, like I already do in my Python apps.

In particular I would like to know how, with RxRust, I can go back to the original thread if I change the scheduler using the `subscribe_on` operator.
In RxPy I can go back to the GTK mainloop with `observe_on(GtkScheduler(GLib))`. This is necessary because GTK widgets can be updated only from the main thread.

Is there already something similar with RxRust?

**Comment by M-Adoo** [comment]
`rxRust.` not provide a direct way to back main thread.  But you can still use a similar way to do that If your code run in main thread. You can also implement a self Scheduler.

```rust
use rxrust::prelude::*;
use futures::{ future, executor::LocalPool };

let mut local_scheduler = LocalPool::new();

observable::of(1)
  ...
  // Always go back to the thread of `local_scheduler`
  .observer_on(local_scheduler.spawner())
  .subscribe(...)

```

**Comment by leinardi** [comment]
Hey, thanks for the quick response!

So, just to be sure that I get it right, to run an observable on a new thread and observe on the original thread, I could do something like this?

```rust
let pool_scheduler = ThreadPool::new().unwrap();
let mut local_scheduler = LocalPool::new();
observable::from_iter(0..10)
  .subscribe_on(pool_scheduler.clone())
  .map(|v| v*2)
  .to_shared()
  .observer_on(local_scheduler.spawner())
  .to_shared()
  .subscribe(|v| {println!("{},", v)});
```

**Comment by M-Adoo** [comment]
Yes. you are right.
