### ISSUE TITLE
doesn't work on Rust's stable release channel?

### ISSUE THREAD

**Issue by zertyz** [rxRust/rxRust#134]
Thanks for sharing the lib.

Tried to follow the docs on crates.io and, when compiling, I got:

error[E0554]: `#![feature]` may not be used on the stable release channel
at rxrust-0.10.0/src/lib.rs:2:1

It would be nice to add why using the non stable Rust would be a good idea and why this dependency requires it...
and, if possible, to give an estimate when this library may become usable by the stable Rust -- when it will be "Production Ready".

**Comment by M-Adoo** [comment]
The main dependencies are `min_specialization` and `generic_associated_types`.  I would glad to let `rxRust` work on stable 
but there is no exact time.

**Comment by helgoboss** [comment]
I was wondering:

1. Would it be possible to make at least a subset of rxRust work with stable Rust? Or are these unstable features fundamental in a way that this is impossible?
2. When not using these unstable features, would rxRust just be less convenient to use or wouldn't it be possible *at all*?

@M-Adoo What do you think?

**Comment by M-Adoo** [comment]
It's possible. The major problem is `InnerDeref`  depends on GAT.  `InnerDeref` designed  for reuse code between local and shared version. We can disable or remove it on stable, but some code should refactor,  either two version implementation or macro we should use.

**Comment by helgoboss** [comment]
Thanks for your response. Unfortunately I don't have the capacity to help with this at the moment but at some point I would like to. Good to know that there's some hope. Sometimes the search for a well working nightly version of Rust can be quite hard and updating is a true adventure because you won't know what could be messed up ;)

**Comment by helgoboss** [comment]
This is groundbreaking! Thanks @MarcusGrass and @M-Adoo! Looking forward to try it.

**Comment by kapolos** [comment]
`0.12.0` which is the latest on crates.io does not seem to include the merged pr? @M-Adoo 

![image](https://user-images.githubusercontent.com/10794126/120811243-6fe2ee80-c554-11eb-97e5-482f6b88fea4.png)

**Comment by M-Adoo** [comment]
> `0.12.0` which is the latest on crates.io does not seem to include the merged pr? @M-Adoo
> 
> ![image](https://user-images.githubusercontent.com/10794126/120811243-6fe2ee80-c554-11eb-97e5-482f6b88fea4.png)

No, I'll release 0.13.0 today.
