### ISSUE TITLE
Module `interval` is private

### ISSUE THREAD

**Issue by dpietrzyk** [rxRust/rxRust#135]
Hi! 
Thanks for sharing this library!

# Problem
I would like to periodically (e.g. every 5 min) fetch some data.
This data will be transformed etc, that's why I want to encapsulate the whole logic inside one method and be able to create/expose `Observable` which will be emitting transformed data structure.

Unfortunately, when I want to return "`Stream`" from function I receive error `error[E0603]: module 'interval' is private`

# Simple code example
A simplified version of my problem:

```Rust
use rxrust:: prelude::*;

use rxrust::ops::map::MapOp;
use futures::executor::{LocalSpawner, LocalPool};
use std::time::Duration;

// use rxrust::observable::interval::IntervalEmitter;          // <-- error[E0603]: module `interval` is private
// use rxrust::prelude::observable::interval::IntervalEmitter; // <-- error[E0603]: module `interval` is private
use rxrust::prelude::interval::IntervalEmitter;                // <-- error[E0603]: module `interval` is private

pub fn get_data_stream() -> MapOp<ObservableBase<IntervalEmitter<LocalSpawner>>, fn(usize) -> i8> {
    let mut local_scheduler = LocalPool::new();
    let duration = Duration::from_secs(1);

    let int = interval(duration, local_scheduler.spawner())
        .map(|_| 4);

    local_scheduler.run();

    int
}

```

Produce error:
![image](https://user-images.githubusercontent.com/32246156/109398295-4eaea880-793c-11eb-865b-2409b5168ffb.png)

# This is a bug or feature? :see_no_evil: 
I am quite new in Rust world (I came from JS world where RxJs library is well known) and I am not sure  if I am doing sth incorrect or there is a bug in this library :sob: 

I will be grateful for any help :pray:

**Comment by M-Adoo** [comment]
Thanks！ I think we should export it.

**Comment by dpietrzyk** [comment]
@M-Adoo great :) 
Is there a possibility to fix this fast? 
Or can I somehow easily bypass this issue locally to time when it will be fixed?

**Comment by M-Adoo** [comment]
This is an easy bug to fix,  just remove the `crate` of `pub(crate) mod interval;` in the file `observable.rs`. I'll fix it  today or tomorrow.  

And maybe you can try the `impl` syntax:

```
pub fn get_data_stream() -> impl LocalObservable<Item=i8, Err=()> 
```


A pr is very welcome.

**Comment by M-Adoo** [comment]
v0.11.0 released to fix it.
