### ISSUE TITLE
[Suggestion] Upgrade tokio version

### ISSUE THREAD

**Issue by skyao** [rxRust/rxRust#146]
Current version is 0.2.22:

```
[dependencies.tokio]
version = "0.2.22"
```

And the latest version of tokio is 1.7.1

https://github.com/tokio-rs/tokio/releases

Is there any plan to upgrade tokio version?

**Comment by M-Adoo** [comment]
yes of course.

**Comment by skyao** [comment]
Great. 

So what' the plan?

It seems that there is no big changes in tokio api from 0.2 to 1.7.

**Comment by M-Adoo** [comment]
There is no deadline, and nobody depend on it. Maybe I will do it in next month. Pull request is very welcome.
