### ISSUE TITLE
How can I return an observable sequence from a function declared in a trait?

### ISSUE THREAD

**Issue by venth** [rxRust/rxRust#159]
Hi,

I have a case as follows:
```
pub trait Foo {
  fn foo(&self) -> Box<dyn rxrust::Observable<Item=Bar, Err=()>>;
}
```
I cannot return boxed trait because of `Sized` constraint. What options do I have to return a sequence as a function result. I know that:
```
fn foo() -> impl rxrust::Observable<Item=Bar, Err=()> { ... }
```
will work, but I need the function `foo` to be struct bound.

How can I return an observable sequence from a function declared in a trait?

**Comment by M-Adoo** [comment]
You can return  `LocalBoxOp` or  `SharedBoxOp` which returned from  `box_it` operator.

**Comment by venth** [comment]
Thanks 👍 What is the different between `LocalBoxOp` and `SharedBoxOp`?
