### ISSUE TITLE
How can I return multiple type of observable in the same function?

### ISSUE THREAD

**Issue by wufniks** [rxRust/rxRust#175]
Let say I want to make function like following,

```rust
  fn foo(condition: bool) -> Box<dyn Observable<Item=i32, Err=()>> {
    if condition {
      Box::new(observable::of(100))
    }
    else {
      Box::new(observable::of(100).map(|x| x+1))
    }
  }
```

This is not possible now, because `Observable` trait is not object safe.
But, from what I understand, it was object safe before `Sized` maker is deleted in the commit `49503e7`.
I get that deleting `Sized` marker made API's a lot cleaner, but I am wondering if we can bring back object safety of `Observable`.
Or, please let me know if there are some way of doing such things without using trait object.

**Comment by M-Adoo** [comment]
Maybe you want `box_it` operator, and the example in comments may help you.

**Comment by wufniks** [comment]
Thank you a lot for the help and really fast answer!
