### ISSUE TITLE
`wasm` support

### ISSUE THREAD

**Issue by jquesada2016** [rxRust/rxRust#177]
It was brought up in a comment in #176 that `wasm` has not been tested. I believe it would be a fantastic idea to get support for `wasm`, specifically the `wasm32-unknown-unknown`, since the observable spec lends itself most useful to reactive front-end web frameworks, which can currently only target `wasm32-unknown-unknown`.

**Comment by jquesada2016** [comment]
I don't know how, but completely missed the other `wasm` support issue. This issue is a duplicate of #118.

**Comment by M-Adoo** [comment]
#187 fix it.
