### ISSUE TITLE
What is the correct way to construct an observable trait object?

### ISSUE THREAD

**Issue by jquesada2016** [rxRust/rxRust#181]
I have a situation where I often need to accept a list of observables but cannot figure out a common trait between them that is object safe. Specifically, subscribing to a `dyn Observable`, where sometimes `Item` is a specific type, and other times a generic one.

any help would be appreciated.

**Comment by jquesada2016** [comment]
I found the solution for half my problem, which was `BoxObserver`, but since I need to specify the associated types `Item` and `Err`, I'm not able to have a generic collection of observables.

**Comment by M-Adoo** [comment]
Yes, you should use `BoxObserver`.

> where sometimes Item is a specific type, and other times a generic one. 

I don't think you can store them in a same collection, rust not allowed you do it.  Maybe you can unify them with   `enum` ?
