### ISSUE TITLE
Struggling to return an observable from a function

### ISSUE THREAD

**Issue by ntrp** [rxRust/rxRust#192]
I can use the library by specifying the whole chain:
```rust
from_iter(1..3).subscribe(|v| print!("{}", v))
```
But if I try to return the intermediate value it does not work:
```rust
pub fn get_ob() -> ObservableBase<IterEmitter<SensorEmitter>> {
  from_iter(1..3)
}
```
This is the type returned by `from_iter` but IterEmitter is private so I cannot find a return type that works.. How am I supposed to use it?

**Comment by M-Adoo** [comment]
Maybe  use impl trait like `impl LocalObservable<...>` or `impl SharedObservable<...>`,  also a  `box_it` op can box any observable to same type. See `box_it.rs` file.

**Comment by ntrp** [comment]
In the meantime I switched to pure async streams since it was enough for my needs but I will look into you suggestions
