### ISSUE TITLE
`group_by` subscribes again on each new group

### ISSUE THREAD

**Issue by AntonOellerer** [rxRust/rxRust#201]
Hey,
While writing a short program which should feed objects read from a TCP connection into a stream, I noticed that there
seems to be an issue with the `group_by` operator, which results in it not completing. (No output is printed)
Do you know how to solve this, or whether this is a bug in the operator?
```Rust
#[cfg(test)]
mod tests {
    use std::net::TcpListener;
    use rxrust::prelude::*;

    #[test]
    fn it_groups_with_tcp_listener() {
        let mut obs_count = 0;
        observable::create(|subscriber| {
            if let Ok(_) = TcpListener::bind("127.0.0.1:8080") {
                subscriber.next(1);
                subscriber.complete();
            };
        })
        .group_by(|value: &i64| *value)
        .subscribe(move |group| {
            group.subscribe(|_| {
                obs_count += 1;
            });
        });
        assert_eq!(1, obs_count);
    }
}
```
Best regards
Anton Oellerer

**Comment by AntonOellerer** [comment]
During debugging I discovered that when using `if TcpListener::bind("127.0.0.1:8080").is_ok()` instead of the `if let` construct, I receive output, but this is insofar not useful, as I need the listener for receiving packets in the real-world scenario.

**Comment by AntonOellerer** [comment]
Ok, I think the issue may be that each new group calls `subscribe` on the `create` method again, and multiple creation of
the listener fails, so the `GroupObservers` never see a valid value?
This does not explain why it works with `if TcpListener::bind("127.0.0.1:8080").is_ok()` though as far as I can tell

**Comment by AntonOellerer** [comment]
On further consideration, this probably happens because the ports gets freed again quick enough for the next bind to succeed?

**Comment by M-Adoo** [comment]
When you move capture `obs_count` in  the closure, it modify on an copy of `obs_count` not the origin one.  Try to remove the `move` .
```
.subscribe(move |group| {
    group.subscribe(|_| {
        obs_count += 1;
    });
});
```

**Comment by M-Adoo** [comment]
@AntonOellerer Sorry for the late reply, I only have time to make a careful diagnosis today. It's a bug of `group_by` and you are right. `group_by` should not subscribe multi times to upstream and just do a items dispatch is enough.  Would you like to complete your pull request？

**Comment by AntonOellerer** [comment]
@M-Adoo thank you for the confirmation!

I worked on it for quite some time now, but I am afraid implementing this is above my skill.
The problem I can not get past is that both the `GroupByOp` and the subscribing `Observer` would need to own the subgroups. The `GroupByOp` so that it can forward values to it, and the `Observer` so that it can write an observable to it.
Do you maybe have a solution to the problem?

**Comment by AntonOellerer** [comment]
I came a bit further employing `unsafe` code, but there is still a problem with the lifetime of the observer in there sadly (also it is not cleaned up at all)

**Comment by M-Adoo** [comment]
> @M-Adoo thank you for the confirmation!
> 
> I worked on it for quite some time now, but I am afraid implementing this is above my skill. The problem I can not get past is that both the `GroupByOp` and the subscribing `Observer` would need to own the subgroups. The `GroupByOp` so that it can forward values to it, and the `Observer` so that it can write an observable to it. Do you maybe have a solution to the problem?

Usually, you should bounds the value generic type with lifetime. Please push your code and point out where is the problem, maybe I can help you.

**Comment by AntonOellerer** [comment]
I submitted a preliminary PR in #202, containing the mentioned problem and with neither cleaned up code nor cleaned up commit history :sweat_smile:

**Comment by AntonOellerer** [comment]
Managed to remove the unsafe code

**Comment by AntonOellerer** [comment]
Introduced explicit lifetimes in the hope of fixing the problem, am now running into different problems re: longetivity of objects

**Comment by M-Adoo** [comment]
will comment in #202
