### ISSUE TITLE
Use Infallible instead of unit for represent an error that will not happen

### ISSUE THREAD

**Issue by Neo-Ciber94** [rxRust/rxRust#222]
Currently for representing the absense of errors `()` unit is being used, but the idiomatic way Rust use for those cases is the `never` type or `Infallible`: https://doc.rust-lang.org/std/convert/enum.Infallible.html

I think `Infallible` is the type which should be used for those cases.

So types like `ObserverItem<N>` should be rewriten as:

```rust
#[derive(Clone)]
pub struct ObserverItem<N> {
  next: N,
}

impl<Item, N> Observer<Item, Infallible> for ObserverItem<N>
where
  N: FnMut(Item),
{
  fn next(&mut self, value: Item) {
    (self.next)(value);
  }

  #[inline]
  fn error(self, _err: Infallible) {}

  #[inline]
  fn complete(self) {}

  #[inline]
  fn is_finished(&self) -> bool {
    false
  }
}
```

**Comment by M-Adoo** [comment]
I agree and do you want to create a pr about this issue?
