### ISSUE TITLE
from_fn | Correctly typing result

### ISSUE THREAD

**Issue by Aderinom** [rxRust/rxRust#226]
Hello Team! 

First of all, I am relatively new to rust, so please do bear with me.

Following problem:
I'm trying to create composable functions which use observables as a streaming mechanism.

e.g.
```rust
fn some_composable_stream() -> ???? {
    observable::create(|mut subscriber: Subscriber<????>| {
        let mut counter = 0;
        while counter < 1000 {
            counter += 1;
            subscriber.next(counter);
            sleep(Duration::from_millis(50));
        }

        if (counter > 1000) {
            subscriber.error("Guess numbers are broken now")
        } else {
            subscriber.complete();
        }
    })
}
```

However - Problem 
1. to just use the resulting observable as a type I need to declare the Item and Err since without the subscribe function rust complains that It can not infer the generic.
2. to properly return the observable I'll also need the correct type.

I've tried a lot of variations now but I am pretty stuck on how to define the type correctly. 

Maybe you are able to give me some assistance here.

**Comment by M-Adoo** [comment]
There are two way for your case:

1.  you can use `impl trait` to return the type, and use a generic type `O`, so you can detect it until use it.
   ```rust 
        fn some_composable_stream<O: Observer<i32, &'static str>>(
        ) -> impl Observable<i32, &'static str, O> + ObservableExt<i32, &'static str> {
          observable::create(|mut subscriber: Subscriber<O>| {
               // ....
          })
        }
   ```
2.  use a `BoxOp` to return, this erased the type information and box a trait in it.

  ``` rust
  fn some_composable_stream() -> BoxOp<'static, i32, &'static str> {
    observable::create(|mut subscriber: Subscriber<_>| {
          // ...
    })
    .box_it()
  }
  ```

Remember, use it with `on_error`,

```
  some_composable_stream()
    .on_error(|err| {})
    .subscribe(|v| { });
```

**Comment by Aderinom** [comment]
Thank you a lot!
