### ISSUE TITLE
merge_all should support observables which error

### ISSUE THREAD

**Issue by cmfcmf** [rxRust/rxRust#238]
Currently, this code doesn't compile, because the inner observable has an `Error` type that is not `Infallible`, which causes `merge_all` to fail:

```rs
rxrust::observable::empty()
        .map(|_| rxrust::observable::of_result(Err("An error")))
        .merge_all(1)
        .on_error(|e| println!("Error:  {},", e))
        .subscribe(|_| {});
```

I'd expect this to work, and to emit an error on the outer observable if any inner observable errors.

From the RxJS docs: 

> Any error delivered by a inner Observable will be immediately emitted on the output Observable.
> https://rxjs.dev/api/operators/mergeAll

**Comment by cmfcmf** [comment]
Ahh, after further back and forth, I now realized that this happens when the error type of the outer observable is not equal to the error type of the inner observable. This code works:

```rs
rxrust::observable::empty()
    .on_error_map(|_| "not reached") // added
    .map(|_| rxrust::observable::of_result(Err("An error")))
    .merge_all(1)
    .on_error(|e| println!("Error:  {},", e))
    .subscribe(|_| {});
```

I wonder if `merge_all` could do this automatically if the outer error type is `Infallible`?

**Comment by M-Adoo** [comment]
No, we handle values ​​and errors separately, which is very clear and easier to understand. I don't want to add a special case for `Infallible`.

**Comment by cmfcmf** [comment]
Okay, fair enough:)
