### ISSUE TITLE
next_by on a cloned BehaviourSubject holds bad state

### ISSUE THREAD

**Issue by aggalex** [rxRust/rxRust#248]
consider the following passage:

```rust
use rxrust::prelude::*;
let mut behavior = BehaviorSubject::<i32, Subject::<_, _>>::new(0);
behavior.clone().subscribe(|value| println!("{value}"));
behavior.next(7);
for i in 0..10 {
    behavior.clone().next_by(|n| n + 1);
}
println!("{}", behavior.peek());
```

The expected output would be:
```
0
7
8
9
10
11
12
13
14
15
16
17
17
```

Instead, it outputs:
```rust
0
7
8
8
8
8
8
8
8
8
8
8
7
```

If you don't clone the BehaviorSubject before using next_by, it works as expected.

**Comment by M-Adoo** [comment]
We should share the value in the `BehaviorSubject`

**Comment by aggalex** [comment]
What do you think would be the best way to do this? An `Arc<Mutex<Item>>` in the Item field, or somehow else to avoid mutexes?

**Comment by M-Adoo** [comment]
We use `Arc<Mutex<...>>` for shared version and `Rc<RefCell<...>>` for non-shared version.
We have a `RcDerefMut` trait to abstract over `Arc<Mutex<...>>` and `Rc<RefCell<...>>`. You can see the `rc.rs` file.
