### ISSUE TITLE
Unit tests fail when running in docker container

### ISSUE THREAD

**Issue by achary** [rxRust/rxRust#26]
When cloned `master` branch (dec6bffcca66a155a5452273078012350b04ad4d SHA)
and run in docker container (`rustlang/rust:nightly-buster-slim` from [Docker Hub here](https://hub.docker.com/r/rustlang/rust/tags)) then the unit test execution with `cargo test` fails throwing few errors.

Most of them seem to be because of sleep-based timing used in the testing code.
It really looks like timing characteristic of those tests cannot be met in some environments (in this case - my machine + docker container).

Here is an example trace:

```
---- ops::throttle_time::smoke stdout ----
thread 'ops::throttle_time::smoke' panicked at 'assertion failed: `(left == right)`
  left: `[9, 18, 26, 32, 41, 51, 61, 71, 78]`,
 right: `[9, 19, 29, 39, 49, 59, 69, 79, 89, 99]`', src/ops/throttle_time.rs:202:3
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:202
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  14: rxrust::ops::throttle_time::smoke
             at src/ops/throttle_time.rs:202
  15: rxrust::ops::throttle_time::smoke::{{closure}}
             at src/ops/throttle_time.rs:184
  16: core::ops::function::FnOnce::call_once
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libcore/ops/function.rs:227
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/liballoc/boxed.rs:942
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  19: std::panicking::try
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/panicking.rs:265
  20: std::panic::catch_unwind
             at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/panic.rs:396
  21: test::run_test_in_process
             at src/libtest/lib.rs:570
  22: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:473
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    ops::subscribe_on::test::new_thread
    ops::throttle_time::smoke
```

Sometimes these errors are due to really near misses, like:

```
---- ops::throttle_time::smoke stdout ----
thread 'ops::throttle_time::smoke' panicked at 'assertion failed: `(left == right)`
  left: `[9, 18, 28, 38, 48, 58, 68, 78, 88, 98]`,
 right: `[9, 19, 29, 39, 49, 59, 69, 79, 89, 99]`', src/ops/throttle_time.rs:202:3
stack backtrace:
...
```
being off by a single millisecond, but still.

**Comment by achary** [comment]
As an observation - similar failures are happen every now and then on CI, but rarely.

**Comment by M-Adoo** [comment]
Yes, this because timing. Use a large duration maybe resolve it.  I think we should use a fake timer for test in finally, test should also not really sleep true time.  If we need wait seconds, test need run seconds, need test years, test run years...

**Comment by achary** [comment]
I completely support introducing a virtual time scheduler for tests (but also is useful for writing production code that e.g. replays historical data where timestamps where known).
This is how rxCpp guys are testing it, [like here for example](https://github.com/ReactiveX/RxCpp/blob/ce8db91b60e4ca7750a3ec58c3add708f7c5abc6/Rx/v2/test/operators/debounce.cpp#L82) . Not sure for other frameworks.
I find testing any time-aware operator later on almost impossible without being able to precisely pause and advance the time, then see what happen step by step etc.

**Comment by M-Adoo** [comment]
Because rxRust has many other basic work to do, I will not put this matter at a high priority.

**Comment by ehiggs** [comment]
Tarpaulin also slows down the code making timer issues get exposed.

**Comment by ehiggs** [comment]
I took a look at using [fake_clock](https://crates.io/crates/fake_clock) but the clocks are thread local so I don't think it can work to tell the ThreadPool Scheduler to use the fake clock. #50 has a block_on method request that would otherwise fix the flakiness.

**Comment by M-Adoo** [comment]
@ehiggs thanks for what you doing, both fake timer and block_on we should have.
