### ISSUE TITLE
How does this interop with Rust's async ecosystem?

### ISSUE THREAD

**Issue by lqf96** [rxRust/rxRust#51]
I'm very curious about how this project will interoperate with Rust's async ecosystem? Specifically, what's the relation between Observables and `future-rs`'s Streams, and Operators and Stream combinators? It seems that both can represent a series of asynchronous values, and we probably want to avoid duplicate work here.

**Comment by M-Adoo** [comment]
We support convert from a `Future` to `Observable` now, and will support convert from `future-rs`'s  Streams to Rx's Stream.

In a simple way Rx is a push model and Future is a pull model,  like process ui events, push model is more comfortable to use. There is some discuss in [Does Rust need Rx implementation (and/or more)?](https://users.rust-lang.org/t/does-rust-need-rx-implementation-and-or-more/29481)

**Comment by lqf96** [comment]
Yeah that makes sense. So `RxRust` will be the implementation of `ReactiveX` for Rust and `futures-rs` is more similar to [`IxJS`](https://github.com/ReactiveX/IxJS) that is pull-based. Both will a similar set of operators though. Is that correct?

**Comment by M-Adoo** [comment]
`rxRust` will be the implementation of ReactiveX for Rust，but i don't know if  `futures-rs`'s stream is similar to `IxJs`, I don't know much about `IxJs`.
