### ISSUE TITLE
Consider renaming `Fork`

### ISSUE THREAD

**Issue by ishitatsuyuki** [rxRust/rxRust#61]
`Fork` seems to be a name that no one is familiar with. It's also confusing because it isn't exactly multicast as you would imagine from the word "fork".

I'd suggest that we just make it `Clone` (with a bound) instead. Does that make sense and would that work with the current implementations?

**Comment by M-Adoo** [comment]
I agree with `Fork` is not the best choice, neither  `Clone`.  In now `Fork` not  force require  the fork type is `Self`, is also not a clone mean. A better name we should find.

**Comment by ishitatsuyuki** [comment]
I don't understand what you're trying to say in the previous comment. What's your definition of `Fork`? The implementation looks like it's cloning everything inside, so it seems to match `Clone`.

`ForkObservable` seems to be doing type erasure, which wasn't something I expected. Did you designed `Fork` as a way to use dynamically-dispatched observable types?

**Comment by M-Adoo** [comment]
`Fork` designed for subscribe a stream multi times, and not care how operator implement it.
