### ISSUE TITLE
IntoShared on LocalSubscription uses unneeded transmute

### ISSUE THREAD

**Issue by ishitatsuyuki** [rxRust/rxRust#64]
This line of transmute is unsound:

https://github.com/rxRust/rxRust/blob/7b557528a47a83603d88b37c8b3735d711b1cccb/src/subscription.rs#L61

Basically it adds the `Send + Sync + 'static` bound to the `dyn SubscriptionLike` without verifying if it holds. In the current implementation there's no way to do this conversion safely, so either the `impl IntoShared` has to be removed or `LocalSubscription` and `SharedSubscription` should get a rewrite.

**Comment by M-Adoo** [comment]
It's an unnecessary code.  `LocalSubscription` it's can convert into `SharedSubscription ` only if its teardown size is empty. I'll fix it.

**Comment by ishitatsuyuki** [comment]
Oh yeah, didn't realize this. You're correct.
