### ISSUE TITLE
Using MutRefSubject can easily cause heap corruption

### ISSUE THREAD

**Issue by helgoboss** [rxRust/rxRust#79]
This happens in a real-world use case: In my application I have an `AppSession` struct which is like a singleton, so it pretty much outlives everything else. It contains a subject to which I want to publish some events over time. I want these events to be references because at the time of pushing the event I'm in a constrained thread (audio thread) where heap allocation is bad and too much copying should be avoided. In rxRust we have `MutRefItemSubject` so I thought I give it a try (although actually I only need immutable references, not mutable references). The events are very short-lived and only valid until the call to `next()` returns.

The problem is, I can't get the lifetimes right. Even worse, it's very easy to get heap corruptions. Here's some reduced test code which likely causes a corruption:

```rust
  #[test]
  fn heap_corruption() {
    // Preparation
    #[derive(Debug)]
    struct Event(String);

    impl Drop for Event {
      fn drop(&mut self) {
        println!("Dropped {:?}", self)
      }
    }

    struct AppSession {
      event_subject: MutRefItemSubject<'static, Event, ()>
    }

    impl AppSession {
      pub fn publish_event(&mut self, evt: &mut Event) {
        self.event_subject.next(evt)
      }
    }

    // Do some things
    let mut app_session = AppSession {
      event_subject: LocalSubject::new().mut_ref_item()
    };
    let mut previous_events: Vec<&mut Event> = vec!();
    app_session.event_subject.clone().subscribe(move |current_event| {
      if !previous_events.is_empty() {
        println!("Previous events were: {:?}", previous_events);
        // This is the final straw. Without this line it sometimes work, but only because we 
        // are lucky. The actual root issue however is at DANGER comment.
        previous_events.iter_mut().for_each(|evt| evt.0.push_str(" modified"))
      }
      println!("Got new event: {:?}\n", current_event);
      // DANGER: This is bad. Ideally, that shouldn't be possible, but it is.
      previous_events.push(current_event);
    });
    {
      let mut short_living_event = Event(String::from("1"));
      app_session.publish_event(&mut short_living_event);
    }
    {
      let mut short_living_event = Event(String::from("2"));
      app_session.publish_event(&mut short_living_event);
    }
  }
```

See the DANGER comment. Here I would expect that current_event is exposed with a lifetime that doesn't exceed the observer's `next` method call. Then Rust compiler would not compile this code.

@M-Adoo I know this is made possible because of the `unsafe` line in `mut_ref_subject.rs` ... do you think there's a safe way of implementing (mut) ref subjects?

**Comment by M-Adoo** [comment]
You are right, It's not safe, mut_ref_subject erase the lifetime of the &'_ mut item. You shouldn't store the mut ref item from subject.  And  we also need mark the mut_ref_item method as unsafe.

**Comment by M-Adoo** [comment]
close by #98
